apiVersion: v1
kind: Pod
metadata:
  namespace: sanyam
  labels:
    run: web222
  name: web222
spec:
  containers:
  - image: nginx
    name: web222
    ports:
    - containerPort: 80
    volumeMounts:
     - name: myvol
       mountPath: /usr/share/nginx/html/

  volumes:
   - name: myvol                          #volume creation
     persistentVolumeClaim:
      claimName: mypvc
