apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod 
  labels:
    name: nfs-pod
spec:
  containers:
    - name: c1
      image: nginx
      ports:
        - name: web
          containerPort: 80
      volumeMounts:
        - name: nfsvol 
          mountPath: /usr/share/nginx/html 
 
  volumes:
    - name: nfsvol
      persistentVolumeClaim:
        claimName: nfs-pvc 
