apiVersion: v1
kind: Pod
metadata:
  name: hellosamplepod100000000
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: c1
    ports:
    - containerPort: 80
  nodeName: node2.example.com # here kube schedular to schedual on specific node
  restartPolicy: Always
